### ISSUE TITLE
Include python setup files in the root directory

### ISSUE THREAD

**Issue by debeshmandal** [lorenzo-rovigatti/oxDNA#7] opened 2020-11-14 15:28 UTC
# Summary

For most users, installation of a Python package takes place using one of three ways:

1. `pip install package` - Installing from PyPi
2. `conda install package` - Installing from an Anaconda source
3. `git clone /path/to/package && pip install package` - downloading the source files and building manually using pip

This issue relates to number 3, allowing Python users (who may not be familiar with building C/C++ packages) to install the package without invoking CMake or any C-based build tools.

## Current State

To install the `oxpy` package, the following steps must be done:

```
git clone https://github.com/lorenzo-rovigatti/oxDNA
cd oxDNA
mkdir build
cd build
cmake .. -DPython=1
make
make install
```

## Upgraded State

The new installation method will be:

```
git clone https://github.com/lorenzo-rovigatti/oxDNA
cd oxDNA
pip install .
```

## Tasks

1. Create a `setup.py` files
2. Investigate the use of other setup files, e.g. `setup.cfg`
3. Investigate how to include build options e.g. `-DCUDA=1`

**Comment by lorenzo-rovigatti** [comment] 2021-01-01 19:17
Thanks to commit 784604b is now possible to compile&install oxpy with `pip` as suggested. I have tested it on my ubuntu 20.04 box and it works as intended.

I still need to find a way of managing the other cmake options such as `-DCUDA=1`. I'm open to suggestions!

**Comment by debeshmandal** [comment] 2021-01-07 00:09
I am going to look into using `pip`  to install and manage `cmake` - I think that it might be quite simple after reading from [here](https://cmake-python-distributions.readthedocs.io/en/latest/building.html) but I will research and reply back on here since I may be misunderstanding exactly what the documentation says

**Comment by lorenzo-rovigatti** [comment] 2021-01-07 10:42
Hey Debesh, note that the `cmake`-`pip` integration has been already carried out in commit 784604b. I think (although am not sure) that the "pythonic" way of setting cmake options would be that of using the `setup.cfg` file.

**Comment by lorenzo-rovigatti** [comment] 2021-02-09 22:46
I have added a way of compiling with CUDA support in  commit f224d74 . It's a bit clunky but it works: the user can either uncomment the `#cuda = True` line in the `setup.cfg` file or append `--global-option=build_ext --global-option='--cuda'` to the `pip install` command.

**Comment by debeshmandal** [comment] 2021-02-15 17:49
I'm going to take a look at this now and try it on my machine

Is it possible now to use the traditional command line options by doing:

```
python setup.py install --global-option=build_ext --global-option='<options>'
```

Or is it only specific to using `'--cuda'`

**Comment by lorenzo-rovigatti** [comment] 2021-02-15 17:55
It's just `--cuda` right now. I'll need to add the options we want to support by hand. I'm thinking about what's worth adding. Any ideas?

**Comment by debeshmandal** [comment] 2021-02-15 18:12
just tried to do the installation within my anaconda environment and I got this error when importing oxpy:

```python
ModuleNotFoundError: No module named 'oxpy.core'
```

I think I know the reason for this because I had a similar problem with my package [hydrogels](github.com/debeshmandal/hydrogels) - I think that it is just a slight change in one of the keyword arguments in the `setup.py` file:

At the moment it looks like this :

```python
setup(
...
    package_data = {
        'oxpy': ['core.so']
    }
)
```

but in my package I have something like this:

```python
setup(
)
```

**Comment by debeshmandal** [comment] 2021-02-15 18:13
Sorry - accidently made a comment instead of deleting what I had typed!

Just tried the install and everything works well - apologies for any confusion!

**Comment by debeshmandal** [comment] 2021-02-15 18:15
I'm going to start using the Python library version with a Masters student over the next month so I will keep you posted for any issues or improvements I notice

**Comment by lorenzo-rovigatti** [comment] 2021-02-15 18:27
That's great, thank you! I'll leave this issue open if anyone has any suggestions about options to be added or has any issues with the setup.py.

**Comment by lorenzo-rovigatti** [comment] 2021-06-01 08:22
I have now merged this change in the `master` branch. Did you happen to find any bug during your testing/usage?

**Closed** 2022-04-05 16:02 UTC
Labels: enhancement, help wanted
